[package]
name        = "rustdx"
version     = "0.4.0"
edition     = "2021"
license     = "MIT"
description = "受 pytdx 启发的 A 股数据获取库"
repository  = "https://github.com/zjp-CN/rustdx"
authors     = ["zjp <jiping_zhou@foxmail.com>"]
exclude     = [
                "assets", "examples", "benches", "tests", "old",
                "CHANGELOG.md", "*.csv", "*.log", ".github", ".gitignore",
                "rustfmt.toml", "LICENSE"
              ]

[dependencies]
chrono  = {version = "0.4" }
lazy_static = {version = "1" }
miniz_oxide = {version = "0.7" }

# anyhow = "1"
thiserror = "1"
log = {version = "0.4" }

[dependencies.serde]
version  = "1"
features = ["derive"]
# default-features = false

[dependencies.encoding_rs]
version  = "0.8"
features = ["fast-gb-hanzi-encode"]

[dev-dependencies]
# backtrace 是在 cargo test 无法并行的情况下 用于产生 test name （从而产生 snapshot name ）
insta = "1"
version-sync = {version = "0.9", default-features = false, features = ["html_root_url_updated"]}
csv = "1"

[profile.bench]
lto = true
opt-level = 3

[profile.release]
lto = true
opt-level = 3

[workspace]
members = ["rustdx-cmd"]

[package.metadata.docs.rs]
all-features = true
