[package]
name        = "rustdx-cmd"
version     = "0.3.0"
edition     = "2018"
license     = "MIT"
build       = "build.rs"
readme      = "../README.md"
description = "受 pytdx 启发的 A 股数据获取库"
repository  = "https://github.com/zjp-CN/rustdx"
authors     = ["zjp <jiping_zhou@foxmail.com>"]
exclude     = [
                "assets", "examples", "benches", "tests", "rustdx.log", "*.csv",
                "LICENSE-MIT", "rustfmt.toml"
              ]

[dependencies]
anyhow   = "1"
argh     = {version = "0.1" , optional = true}
calamine = {version = "0.19", optional = true}
futures  = {version = "0.3" , optional = true}
tokio    = {version = "1", features = ["rt-multi-thread", "macros"]   , optional = true}
# rustdx   = {path    = "../" , optional = true}
reqwest  = {version = "0.11", optional = true}
bytes    = {version = "1.1" , optional = true}
csv      = {version = "1.1" , optional = true}
log      = {version = "0.4" , optional = true}
chrono   = {version = "0.4" , optional = true}
serde_json  = {version = "1", optional = true}
lazy_static = {version = "1", optional = true}
mini-redis  = {version = "0.4", optional = true}
subprocess  = {version = "0.2", optional = true}
simplelog   = {version ="0.12", optional = true}
miniz_oxide = {version ="0.7", optional = true}

[dependencies.rustdx]
version  = "0.3.0"
optional = true
path = "../"
default-features = false
features = ["serde", "file"]

[dependencies.serde]
version  = "1"
optional = true
features = ["derive"]

[features]
default = ["bin"]
bin = ["rustdx", "tokio/rt",  "tokio/rt-multi-thread", "futures", "argh", "calamine", "lazy_static", "reqwest", "csv", "subprocess", "reqwest/json", "serde", "serde_json", "chrono"]
excel = ["calamine", "reqwest", "tokio/rt",  "tokio/rt-multi-thread", "futures"]
clickhouse = ["tokio/macros", "tokio/sync", "csv"]

[[bin]]
name = "rustdx"
path = "src/main.rs"
required-features = ["bin"]

[[example]]
name = "excel"
path = "examples/excel.rs"
required-features = ["excel"]

[[example]]
name = "excel_and_online"
path = "examples/excel_and_online.rs"
required-features = ["excel"]

[[example]]
name = "clickhouse-cmd"
path = "examples/clickhouse-cmd.rs"
required-features = ["clickhouse"]

[[example]]
name = "tcp"
path = "examples/tcp.rs"
required-features = ["rustdx/tcp"]
